name: My first action

on: 
  push:
    branches: [ main ]

jobs: 
  react_on_push:
     runs-on: ubuntu-latest
     steps:
     - name: Osman
       run: echo "This workflow runs on any push to any branch."
